// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7XzlTkvWhaUev7usLmYwtualuHiPk9Pg',
    appId: '1:642230259456:web:b816538e4bda7d9165ede5',
    messagingSenderId: '642230259456',
    projectId: 'final-project-database-67296',
    authDomain: 'final-project-database-67296.firebaseapp.com',
    storageBucket: 'final-project-database-67296.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgJor9aHgPQbRPIi0KrKqPzl_ih_CwZQM',
    appId: '1:642230259456:android:cd1e589177f555ca65ede5',
    messagingSenderId: '642230259456',
    projectId: 'final-project-database-67296',
    storageBucket: 'final-project-database-67296.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1R96ecSGMIjcrQ3dKr7jzcPXYdaLdIY0',
    appId: '1:642230259456:ios:c1533a2ee0567e6565ede5',
    messagingSenderId: '642230259456',
    projectId: 'final-project-database-67296',
    storageBucket: 'final-project-database-67296.appspot.com',
    iosClientId: '642230259456-e2v62al09aqkm2tip6idg6nrr74k6t32.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFinalProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1R96ecSGMIjcrQ3dKr7jzcPXYdaLdIY0',
    appId: '1:642230259456:ios:c1533a2ee0567e6565ede5',
    messagingSenderId: '642230259456',
    projectId: 'final-project-database-67296',
    storageBucket: 'final-project-database-67296.appspot.com',
    iosClientId: '642230259456-e2v62al09aqkm2tip6idg6nrr74k6t32.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFinalProject2',
  );
}
